### ISSUE TITLE
java.lang.NoSuchMethodError (After server update to 1.18.1)

### ISSUE THREAD

**Issue by Tarlak333** [BerndiVader/mmDenizenAddon#14]
**Hello,**

**MythicDenizenAddon is throwing this ERROR on startup after updating to 1.18.1, all plugins are current Dev builds as of Jan 12th 2022.**

[20:15:14 INFO]: [MythicDenizenAddon] Enabling MythicDenizenAddon v0.605-SNAPSHOT
[20:15:14 ERROR]: Error occurred while enabling MythicDenizenAddon v0.605-SNAPSHOT (Is it up to date?)
java.lang.NoSuchMethodError: 'com.denizenscript.denizen.scripts.commands.BukkitCommandRegistry com.denizenscript.denizen.Denizen.getCommandRegistry()'
	at com.gmail.berndivader.mythicdenizenaddon.MythicMobsAddon.<clinit>(MythicMobsAddon.java:84) ~[MythicDenizenAddon-0.605-45.jar:?]
	at com.gmail.berndivader.mythicdenizenaddon.MythicDenizenPlugin.onEnable(MythicDenizenPlugin.java:46) ~[MythicDenizenAddon-0.605-45.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[paper-api-1.18.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugin(CraftServer.java:564) ~[paper-1.18.1.jar:git-Paper-142]
	at org.bukkit.craftbukkit.v1_18_R1.CraftServer.enablePlugins(CraftServer.java:478) ~[paper-1.18.1.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:727) ~[paper-1.18.1.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:503) ~[paper-1.18.1.jar:git-Paper-142]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:313) ~[paper-1.18.1.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1202) ~[paper-1.18.1.jar:git-Paper-142]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.18.1.jar:git-Paper-142]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:15:14 INFO]: [MythicDenizenAddon] Disabling MythicDenizenAddon v0.605-SNAPSHOT

**Lastest Sever Startup Log:**
https://pastebin.com/aDh4YLKj
